version: '3.9'

services:
  mysql:
    image: mysql:8
    container_name: database
    ports:
      - 3306:3306
    volumes:
      - type: volume
        source: mysql-db
        target: /var/lib/mysql
        volume:
          nocopy: true
    environment:
      - MYSQL_ROOT_PASSWORD=yY6eE#99Hds0
      - MYSQL_PASSWORD=Hh783lK
      - MYSQL_USER=payment
      - MYSQL_DATABASE=payment
volumes:
  thanhtoan-logs:
