version: '2.1'
services:
    thanhtoan:
        container_name: thanhtoan
        image: thanhtoan:latest
        privileged: true
        pid: host
        ports:
            - 8080:8080
        volumes:
            - type: volume
              source: thanhtoan-logs
              target: /var/log/supervisor
              volume:
                nocopy: true
            - type: bind
              source: /data/thanhtoan
              target: /data/thanhtoan
        tty: true
        restart: on-failure
        networks:
            - api-network
networks:
    api-network:
        driver: bridge

volumes:
  thanhtoan-logs:
